### Get Users
GET http://localhost:1234/users?search=gmail.cl

### Get User by ID
GET http://localhost:1234/users/17

### Register user
POST http://localhost:1234/users/register
Content-Type: application/json

{
  "name": "Yennifer Aros",
  "email": "yenni123@gmail.cl",
  "password": "password",
  "password_confirmation": "password"
}

### Create user
POST http://localhost:1234/users
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJuYW1lIjoiQXhlbCBHYWxlYSIsImVtYWlsIjoiYWtzZWxnYWxlYUBnbWFpbC5jbCIsImlhdCI6MTY5MzgzNjE5MX0.hHw-E2bLWPvjhZYRAztnZBdbbJQm_tV4huiP8LeHMBE

{
  "name": "Yennifer Aros",
  "email": "yenni123@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Update user
PATCH http://localhost:1234/users/7
Content-Type: application/json

{
  "name": "Axel Ormeño",
  "email": "ormenhoaxel@gmail.com"
}

### Update user password
PATCH http://localhost:1234/users/31/reset-password
Content-Type: application/json

{
  "oldPassword": "password",
  "password": "password",
  "password_confirmation": "password"
}

### Delete user
DELETE http://localhost:1234/users/14
Content-Type: application/json

{
  "password": "password"
}


### Login user
POST http://localhost:1234/users/login
Content-Type: application/json

{
  "email": "akselgalea@gmail.cl",
  "password": "password"
}