### Create user
POST http://localhost:1234/users
Content-Type: application/json

{
  "name": "Axel Galea",
  "email": "akselgalea@gmail.com",
  "password": "password"
}

### Create user without required fields
POST http://localhost:1234/users
Content-Type: application/json

{
  "name": "Axel Galea",
  "email": "akselgalea@gmail.com"
}

### Create user with extra fields and string too small
POST http://localhost:1234/users
Content-Type: application/json

{
  "sql": "select * from users",
  "name": "Axel Galea",
  "email": "akselgalea@gmail.com",
  "password": "a"
}

### Create user wrong type
POST http://localhost:1234/users
Content-Type: application/json

{
  "name": 1,
  "email": "akselgalea@gmail.com"
}

### Create user string too big
POST http://localhost:1234/users
Content-Type: application/json

{
  "name": "Axel Galea",
  "email": "akselgalea@gmail.com",
  "password": "passwordpasswordpasswordpasswordpasswordpasswordpasswordpassa"
}

### Create user empty
POST http://localhost:1234/users
Content-Type: application/json

{
}